image: jelaniwoods/appdev2023-rails-template

tasks:
  - env:
      DATABASE_URL: "postgresql://gitpod@localhost"
    before: |
      sudo echo 'export DATABASE_URL="postgresql://gitpod@localhost"' | sudo tee -a ~/.bashrc
      sudo cp -r /home/student /home/gitpod && sudo chmod 777 /home/gitpod && chown -R gitpod /home/gitpod
      export GEM_HOME=/workspace/.rvm
      export GEM_PATH=$GEM_HOME:$GEM_PATH
      export PATH=/workspace/.rvm/bin:$PATH
      bin/setup
ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
  - port: 4567
    onOpen: open-preview
    visibility: public
  - port: 9292
    onOpen: open-preview
    visibility: public
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - vortizhe.simple-ruby-erb
    - mbessey.vscode-rufo
    - aliariff.vscode-erb-beautify
    - eamodio.gitlens
    - setobiralo.erb-commenter
